In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('PlayerStatistics.csv')

C:\Users\sthefany.bspina\AppData\Local\Temp\ipykernel_59684\2152893101.py:1: DtypeWarning: Columns (10,11) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('PlayerStatistics.csv')

In [3]:
df.head()

,firstName,lastName,personId,gameId,gameDate,playerteamCity,playerteamName,opponentteamCity,opponentteamName,gameType,...,threePointersPercentage,freeThrowsAttempted,freeThrowsMade,freeThrowsPercentage,reboundsDefensive,reboundsOffensive,reboundsTotal,foulsPersonal,turnovers,plusMinusPoints
0,Mike,Conley,201144,42400231,2025-05-06 21:30:00,Minnesota,Timberwolves,Golden State,Warriors,Playoffs,...,0.00,0.0,0.0,0.000,1.0,0.0,1.0,2.0,0.0,-12.0
1,Stephen,Curry,201939,42400231,2025-05-06 21:30:00,Golden State,Warriors,Minnesota,Timberwolves,Playoffs,...,0.50,0.0,0.0,0.000,1.0,0.0,1.0,0.0,1.0,10.0
2,Jimmy,Butler,202710,42400231,2025-05-06 21:30:00,Golden State,Warriors,Minnesota,Timberwolves,Playoffs,...,0.25,6.0,4.0,0.667,4.0,7.0,11.0,0.0,1.0,15.0
3,Draymond,Green,203110,42400231,2025-05-06 21:30:00,Golden State,Warriors,Minnesota,Timberwolves,Playoffs,...,0.40,2.0,2.0,1.000,8.0,0.0,8.0,5.0,4.0,11.0
4,Rudy,Gobert,203497,42400231,2025-05-06 21:30:00,Minnesota,Timberwolves,Golden State,Warriors,Playoffs,...,0.00,2.0,1.0,0.500,7.0,4.0,11.0,3.0,1.0,-10.0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1626393 entries, 0 to 1626392
Data columns (total 35 columns):
 #   Column                   Non-Null Count    Dtype
---  ------                   --------------    -----
 0   firstName                1626393 non-null  object
 1   lastName                 1626393 non-null  object
 2   personId                 1626393 non-null  int64
 3   gameId                   1626393 non-null  int64
 4   gameDate                 1626393 non-null  object
 5   playerteamCity           1626393 non-null  object
 6   playerteamName           1626393 non-null  object
 7   opponentteamCity         1626393 non-null  object
 8   opponentteamName         1626393 non-null  object
 9   gameType                 1626393 non-null  object
 10  gameLabel                89538 non-null    object
 11  gameSubLabel             3342 non-null     object
 12  seriesGameNumber         134003 non-null   float64
 13  win                      1626393 non-null  int64
 14  home                     1626393 non-null  int64
 15  numMinutes               1465079 non-null  float64
 16  points                   1625174 non-null  float64
 17  assists                  1625174 non-null  float64
 18  blocks                   1625174 non-null  float64
 19  steals                   1625174 non-null  float64
 20  fieldGoalsAttempted      1625174 non-null  float64
 21  fieldGoalsMade           1625174 non-null  float64
 22  fieldGoalsPercentage     1625174 non-null  float64
 23  threePointersAttempted   1625174 non-null  float64
 24  threePointersMade        1625174 non-null  float64
 25  threePointersPercentage  1625174 non-null  float64
 26  freeThrowsAttempted      1625174 non-null  float64
 27  freeThrowsMade           1625174 non-null  float64
 28  freeThrowsPercentage     1625174 non-null  float64
 29  reboundsDefensive        1625174 non-null  float64
 30  reboundsOffensive        1625174 non-null  float64
 31  reboundsTotal            1625174 non-null  float64
 32  foulsPersonal            1625174 non-null  float64
 33  turnovers                1625174 non-null  float64
 34  plusMinusPoints          1625174 non-null  float64
dtypes: float64(21), int64(4), object(10)
memory usage: 434.3+ MB

In [5]:
df.describe()

,personId,gameId,seriesGameNumber,win,home,numMinutes,points,assists,blocks,steals,...,threePointersPercentage,freeThrowsAttempted,freeThrowsMade,freeThrowsPercentage,reboundsDefensive,reboundsOffensive,reboundsTotal,foulsPersonal,turnovers,plusMinusPoints
count,1.626393e+06,1.626393e+06,134003.000000,1.626393e+06,1.626393e+06,1.465079e+06,1.625174e+06,1.625174e+06,1.625174e+06,1.625174e+06,...,1.625174e+06,1.625174e+06,1.625174e+06,1.625174e+06,1.625174e+06,1.625174e+06,1.625174e+06,1.625174e+06,1.625174e+06,1.625174e+06
mean,2.703388e+05,2.540686e+07,2.377536,4.996781e-01,5.005223e-01,2.178817e+01,9.197767e+00,1.960207e+00,3.686055e-01,5.827524e-01,...,1.153023e-01,2.369583e+00,1.784527e+00,4.228037e-01,2.173334e+00,8.523254e-01,3.778613e+00,1.978143e+00,1.033778e+00,-1.224484e-04
std,4.646136e+06,6.499494e+06,2.039595,5.000001e-01,4.999999e-01,1.278417e+01,8.519524e+00,2.545802e+00,8.332762e-01,9.597811e-01,...,2.452721e-01,3.053038e+00,2.451332e+00,4.253676e-01,2.677557e+00,1.387874e+00,3.939210e+00,1.655812e+00,1.403367e+00,7.379388e+00
min,2.000000e+00,1.030000e+07,0.000000,0.000000e+00,0.000000e+00,-5.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,-5.800000e+01
25%,1.733000e+03,2.120025e+07,0.000000,0.000000e+00,0.000000e+00,1.200000e+01,2.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,7.705700e+04,2.510020e+07,2.000000,0.000000e+00,1.000000e+00,2.200000e+01,7.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,2.000000e+00,1.000000e+00,5.000000e-01,1.000000e+00,0.000000e+00,3.000000e+00,2.000000e+00,0.000000e+00,0.000000e+00
75%,2.015880e+05,2.860068e+07,4.000000,1.000000e+00,1.000000e+00,3.200000e+01,1.400000e+01,3.000000e+00,0.000000e+00,1.000000e+00,...,0.000000e+00,4.000000e+00,3.000000e+00,8.560000e-01,3.000000e+00,1.000000e+00,6.000000e+00,3.000000e+00,2.000000e+00,0.000000e+00
max,1.962938e+09,6.240000e+07,7.000000,1.000000e+00,1.000000e+00,9.600000e+01,1.000000e+02,3.000000e+01,1.700000e+01,1.100000e+01,...,1.000000e+00,3.900000e+01,3.000000e+01,1.100000e+01,2.900000e+01,2.100000e+01,5.500000e+01,2.300000e+01,1.400000e+01,5.700000e+01

In [6]:
print(df.isnull().sum())

firstName                        0
lastName                         0
personId                         0
gameId                           0
gameDate                         0
playerteamCity                   0
playerteamName                   0
opponentteamCity                 0
opponentteamName                 0
gameType                         0
gameLabel                  1536855
gameSubLabel               1623051
seriesGameNumber           1492390
win                              0
home                             0
numMinutes                  161314
points                        1219
assists                       1219
blocks                        1219
steals                        1219
fieldGoalsAttempted           1219
fieldGoalsMade                1219
fieldGoalsPercentage          1219
threePointersAttempted        1219
threePointersMade             1219
threePointersPercentage       1219
freeThrowsAttempted           1219
freeThrowsMade                1219
freeThrowsPercentage          1219
reboundsDefensive             1219
reboundsOffensive             1219
reboundsTotal                 1219
foulsPersonal                 1219
turnovers                     1219
plusMinusPoints               1219
dtype: int64

In [7]:
df = df.dropna()

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2589 entries, 0 to 36478
Data columns (total 35 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   firstName                2589 non-null   object
 1   lastName                 2589 non-null   object
 2   personId                 2589 non-null   int64
 3   gameId                   2589 non-null   int64
 4   gameDate                 2589 non-null   object
 5   playerteamCity           2589 non-null   object
 6   playerteamName           2589 non-null   object
 7   opponentteamCity         2589 non-null   object
 8   opponentteamName         2589 non-null   object
 9   gameType                 2589 non-null   object
 10  gameLabel                2589 non-null   object
 11  gameSubLabel             2589 non-null   object
 12  seriesGameNumber         2589 non-null   float64
 13  win                      2589 non-null   int64
 14  home                     2589 non-null   int64
 15  numMinutes               2589 non-null   float64
 16  points                   2589 non-null   float64
 17  assists                  2589 non-null   float64
 18  blocks                   2589 non-null   float64
 19  steals                   2589 non-null   float64
 20  fieldGoalsAttempted      2589 non-null   float64
 21  fieldGoalsMade           2589 non-null   float64
 22  fieldGoalsPercentage     2589 non-null   float64
 23  threePointersAttempted   2589 non-null   float64
 24  threePointersMade        2589 non-null   float64
 25  threePointersPercentage  2589 non-null   float64
 26  freeThrowsAttempted      2589 non-null   float64
 27  freeThrowsMade           2589 non-null   float64
 28  freeThrowsPercentage     2589 non-null   float64
 29  reboundsDefensive        2589 non-null   float64
 30  reboundsOffensive        2589 non-null   float64
 31  reboundsTotal            2589 non-null   float64
 32  foulsPersonal            2589 non-null   float64
 33  turnovers                2589 non-null   float64
 34  plusMinusPoints          2589 non-null   float64
dtypes: float64(21), int64(4), object(10)
memory usage: 728.2+ KB

In [9]:
print(df.dtypes)

firstName                   object
lastName                    object
personId                     int64
gameId                       int64
gameDate                    object
playerteamCity              object
playerteamName              object
opponentteamCity            object
opponentteamName            object
gameType                    object
gameLabel                   object
gameSubLabel                object
seriesGameNumber           float64
win                          int64
home                         int64
numMinutes                 float64
points                     float64
assists                    float64
blocks                     float64
steals                     float64
fieldGoalsAttempted        float64
fieldGoalsMade             float64
fieldGoalsPercentage       float64
threePointersAttempted     float64
threePointersMade          float64
threePointersPercentage    float64
freeThrowsAttempted        float64
freeThrowsMade             float64
freeThrowsPercentage       float64
reboundsDefensive          float64
reboundsOffensive          float64
reboundsTotal              float64
foulsPersonal              float64
turnovers                  float64
plusMinusPoints            float64
dtype: object

In [11]:
df = df.astype({"seriesGameNumber": 'int64', "numMinutes": 'int64', "points": 'int64', "assists": 'int64',
               "blocks": 'int64',"steals": 'int64',"fieldGoalsAttempted": 'int64',"fieldGoalsMade": 'int64',
               "fieldGoalsPercentage": 'int64',"threePointersAttempted": 'int64',"threePointersMade": 'int64',"threePointersPercentage": 'int64',
               "freeThrowsAttempted": 'int64',"freeThrowsMade": 'int64',"freeThrowsPercentage": 'int64',"reboundsDefensive": 'int64',
               "reboundsOffensive": 'int64',"reboundsTotal": 'int64',"foulsPersonal": 'int64',"turnovers": 'int64', "plusMinusPoints": 'int64'})

In [12]:
print(df.dtypes)

firstName                  object
lastName                   object
personId                    int64
gameId                      int64
gameDate                   object
playerteamCity             object
playerteamName             object
opponentteamCity           object
opponentteamName           object
gameType                   object
gameLabel                  object
gameSubLabel               object
seriesGameNumber            int64
win                         int64
home                        int64
numMinutes                  int64
points                      int64
assists                     int64
blocks                      int64
steals                      int64
fieldGoalsAttempted         int64
fieldGoalsMade              int64
fieldGoalsPercentage        int64
threePointersAttempted      int64
threePointersMade           int64
threePointersPercentage     int64
freeThrowsAttempted         int64
freeThrowsMade              int64
freeThrowsPercentage        int64
reboundsDefensive           int64
reboundsOffensive           int64
reboundsTotal               int64
foulsPersonal               int64
turnovers                   int64
plusMinusPoints             int64
dtype: object

In [13]:
df.to_csv("PlayerStatistics2.csv", index=False)